"""add description to common_parameter_template

Revision ID: 03b12dbd803a
Revises: c3e06b32fbeb
Create Date: 2026-04-20 16:37:36.004810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b12dbd803a'
down_revision = 'c3e06b32fbeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('common_parameter_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('common_parameter_template', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
